packaging_format = 2

id = "diagramsnet"
name = "Diagrams.net"
description.en = "Online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams"
description.fr = "Application en ligne qui permet de faire des schémas et du dessin vectoriel"

version = "21.6.6~ynh1"

maintainers = ["Gofannon"]

[upstream]
license = "Apache-2.0"
website = "https://www.diagrams.net/"
demo = "https://app.diagrams.net/"
admindoc = "https://www.diagrams.net/doc"
code = "https://github.com/jgraph/drawio"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/diagram"

    [install.init_main_permission]
    type = "group"
    default = false

[resources]
        [resources.sources.main]
        url = "https://github.com/jgraph/drawio/archive/refs/tags/v21.6.6.tar.gz"
        sha256 = "2ff0fa88613168e0b8afd74c9aa273ca0247a8e999662d9f579ebd2801867fee"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
