packaging_format = 2

id = "diagramsnet"
name = "Diagrams.net"
description.en = "Diagram software for making flowcharts, process diagrams, org charts"
description.fr = "Application qui permet de faire des schémas et du dessin vectoriel"

version = "21.7.5~ynh1"

maintainers = ["Gofannon"]

[upstream]
license = "Apache-2.0"
website = "https://www.diagrams.net/"
demo = "https://app.diagrams.net/"
admindoc = "https://www.diagrams.net/doc"
code = "https://github.com/jgraph/drawio"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/diagram"

    [install.init_main_permission]
    type = "group"
    default = false

[resources]
        [resources.sources.main]
        url = "https://github.com/jgraph/drawio/archive/refs/tags/v21.7.5.tar.gz"
        sha256 = "8f7ac5848231964dfcc9c56a2ed35d67ecc24acf96ae949ef85ba10d097f5c97"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
